name = "Poly"
uuid = "e09f2dfe-59e6-4dd4-bdd5-ac2e3c02424c"
license = "MIT"
authors = ["Evan Patterson <evan@epatters.org>"]
version = "0.1.0"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
